version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    container_name: zero1
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - 5180:5180
      - 6180:6180
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero -o 100 --idx=1 --my=zero1:5180 --tls_enabled_route /state,/removeNode,/moveTablet,/assign,/enterpriseLicense --tls_dir /dgraph-tls
    -v=2 --bindall
volumes: {}